baseurl: /
url: https://thepanlab.github.io


layout: sidebar
style: light

name: The Pan Lab at OU
description: >
  Artificial Intelligence, Supercomputing,
  and Big -Omics Data

theme: just-the-docs
